language: node_js

services:
  - docker

install: true

script:
  - node --version

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t guchong/gucx_subscribe:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID .
  - docker push guchong/gucx_subscribe:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID;
