language: node_js

services:
  - docker

install: true

script:
  - node --version

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID .
  - docker images
