sudo: required

language: node_js

node_js:
  - "lts/*"

branches:
  only:
  - master

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install sshpass

install: true

script:
  - node --version

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t $DOCKER_REPO_SLUG:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID .
  - docker push $DOCKER_REPO_SLUG:$TRAVIS_BRANCH-$TRAVIS_BUILD_ID;
  - sshpass -p $VPS_PASSWORD ssh -o stricthostkeychecking=no -p $VPS_PORT $VPS_USER@$VPS_HOST "sudo /root/work/gitHub/gucx_subscribe/deploy.sh $DOCKER_REPO_SLUG $TRAVIS_BRANCH-$TRAVIS_BUILD_ID tulin-server"
